### PR TITLE
More strictly parse provision file

### PR DESCRIPTION
**Pull request by sunnylqm**
Met an edge case which starts with `<` symbol
xml

### CODE REVIEW

**Comment by chenquincy** [comment]
> Met an edge case which starts with `<` symbol
> xml

Can I get the package to test?

**Comment by sunnylqm** [comment]
Please contact my qq 34731408. thanks

**Comment by chenquincy** [comment]
> Please contact my qq 34731408. thanks

@sunnylqm  Without QQ for a long time, maybe you can send the package to my email: mail@quincychen.cn. Thanks~

**Comment by sunnylqm** [comment]
Sent

**Comment by chenquincy** [comment]
> Sent

Got it, I will check this pr soon. Thanks.

**Comment by chenquincy** [comment]
@sunnylqm v0.3.13 have been published to npm.

**Pull request merged**
