### PR TITLE
Fix some parse error

### PR DESCRIPTION
**Pull request by tiann**
Some apks has no resources.asrc, which may cause error, here is a sample:

[KwCrack.apk.zip](https://github.com/chenquincy/app-info-parser/files/3185076/KwCrack.apk.zip)

### CODE REVIEW

**Comment by chenquincy** [comment]
@tiann  Thanks for your pr, but i think this pr have a problem to discuss.
To fix some apks don't have app icon, i think judge iconPath better than catch an error.
``` javascript
const iconPath = findApkInfoIcon(apkInfo)
if (iconPath) {
  const iconBuffer = await this.getEntry(findApkInfoIcon(apkInfo))
  apkInfo.icon = getBase64FromBuffer(iconBuffer)
} else {
  apkInfo.icon = null
}
```

**Comment by tiann** [comment]
@chenquincy You throw an error in: https://github.com/chenquincy/app-info-parser/blob/master/lib/utils.js#L115

I have no choice but just catch it, may be there are better way, but i am not familiar with the logic in `utils.js`

**Comment by chenquincy** [comment]
@tiann InFact, throw an error in `utils.js` is not a good choice. I will fix it soon. Thanks your for your job.

**Comment by chenquincy** [comment]
@tiann The new version [v0.2.7](https://github.com/chenquincy/app-info-parser/releases/tag/v0.2.7) has been published. I find something can be optimized in [your commit](https://github.com/chenquincy/app-info-parser/pull/18/commits/465050378fc8e172caceddba6a6637f8d563c709) while fix these problems, you can [see more](https://github.com/chenquincy/app-info-parser/commit/2aa636670320936ee5471e2ccfe676a3f9aa13e8) if you interested in it. (Actually icon can't be found without `resources.arsc` file, so we don't need to find it.)

**Pull request merged**
