### PR TITLE
Do not bail out when parsing icon

### PR DESCRIPTION
**Pull request by sunnylqm**

### CODE REVIEW

**Comment by chenquincy** [comment]
@sunnylqm Your pr will make a break change, which maybe affect someone. I think provide a `throwError` option is better. Such as
``` js
parser.parse({
  throwError: true
})
```

**Comment by sunnylqm** [comment]
I think a better way is to make a major version bump.
Since the parsed result is a complex object,  it is normal that some properties may be null/undefined and they should be noted both in doc and type declarations. Any property should be checked before use, which is common in javascript.
If we use errors and even give an option in this parsing process, it won't be helpful in any way. Do we need different errors for different possible missing properties? No matter how we try/catch, in the end we still need to check before use right?

**Comment by chenquincy** [comment]
@sunnylqm Yep, a new major version sounds good. I will update that soon. Thx for your job!

**Comment by chenquincy** [comment]
@sunnylqm v1.0.0 has been published.

**Pull request merged**
